version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 'I l1k3 us1nG p@assphrase @nd h@ck3r sTyl3'
  web:
    build: ./web
    command: bash -c "sleep 5 && gunicorn cake_api.wsgi:application -w 2 -b :8000"
    volumes:
      - "./web/cake_api:/code"
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      APP_ENV: 'development'
      APP_DATABASE_PASSWORD: 'I l1k3 us1nG p@assphrase @nd h@ck3r sTyl3'
      APP_STATIC_ROOT: '/code/static/'
  nginx:
    build: ./nginx
    command: nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    volumes:
      - "./nginx/logs:/var/log/nginx"
  scrap:
    build: ./scrap
    volumes:
      - "./scrap/cake_scrap:/code"
    depends_on:
      - db
    environment:
      APP_DATABASE_PASSWORD: 'I l1k3 us1nG p@assphrase @nd h@ck3r sTyl3'
